import type { ZKBackend, ZKArtifact, ZKWitness, ZKProof } from './types';
import { ZKProofSystem } from './types';

/**
 * SnarkJS-based Groth16 backend.
 *
 * Wraps the snarkjs library for real Groth16 proof generation and verification.
 * Requires snarkjs to be installed as a peer dependency:
 *   pnpm add snarkjs
 *
 * Usage:
 *   const backend = new SnarkJSBackend();
 *   const artifact = await backend.compile('my-circuit', wasmBinary);
 *   const proof = await backend.prove(artifact, witness);
 *   const valid = await backend.verify(artifact, proof);
 *
 * Circuit compilation requires a pre-compiled .wasm and .zkey file pair
 * generated by circom + snarkjs trusted setup. Pass the wasm binary as
 * the `constraints` param to compile(), and store the zkey path in
 * the returned artifact.
 */
export class SnarkJSBackend implements ZKBackend {
  readonly name = 'snarkjs';
  private snarkjs: typeof import('snarkjs') | null = null;
  private zkeyPaths: Map<string, string> = new Map();

  /**
   * @param zkeyDir Directory containing .zkey files named by circuit ID
   */
  constructor(private zkeyDir: string = './circuits') {}

  private async getSnarkJS(): Promise<typeof import('snarkjs')> {
    if (!this.snarkjs) {
      try {
        this.snarkjs = await import('snarkjs');
      } catch {
        throw new Error(
          'snarkjs is not installed. Install it with: pnpm add snarkjs'
        );
      }
    }
    return this.snarkjs;
  }

  /**
   * Compile a circuit from wasm binary.
   * @param circuitId Unique circuit identifier
   * @param constraints The compiled circuit .wasm binary
   * @returns Artifact containing circuit references
   */
  async compile(
    circuitId: string,
    constraints: Uint8Array,
  ): Promise<ZKArtifact> {
    const zkeyPath = `${this.zkeyDir}/${circuitId}.zkey`;
    this.zkeyPaths.set(circuitId, zkeyPath);

    // Extract verification key from zkey
    const snarkjs = await this.getSnarkJS();
    let verificationKey: Uint8Array;

    try {
      const vk = await snarkjs.zKey.exportVerificationKey(zkeyPath);
      verificationKey = new TextEncoder().encode(JSON.stringify(vk));
    } catch {
      // If zkey doesn't exist yet, return empty vkey
      verificationKey = new Uint8Array(0);
    }

    return {
      circuitId,
      provingKey: constraints, // wasm binary stored as proving key
      verificationKey,
    };
  }

  /**
   * Generate a Groth16 proof.
   * @param artifact Compiled circuit artifact (wasm in provingKey)
   * @param witness ZKWitness with public and private inputs
   * @returns ZKProof with Groth16 proof bytes
   */
  async prove(artifact: ZKArtifact, witness: ZKWitness): Promise<ZKProof> {
    const snarkjs = await this.getSnarkJS();
    const zkeyPath = this.zkeyPaths.get(artifact.circuitId);
    if (!zkeyPath) {
      throw new Error(`No zkey path for circuit: ${artifact.circuitId}`);
    }

    // Build input signals from witness
    const inputSignals = this.witnessToSignals(witness);

    // Generate proof using snarkjs
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
      inputSignals,
      artifact.provingKey, // wasm binary
      zkeyPath,
    );

    // Encode proof into 256 bytes: a[2], b[2][2], c[2] as big-endian uint256
    const proofBytes = this.encodeProof(proof);

    // Encode public signals as 32-byte big-endian uint256s
    const publicInputs = publicSignals.map((signal: string) =>
      this.signalToBytes(signal),
    );

    return {
      proofBytes,
      publicInputs,
      system: ZKProofSystem.Groth16,
    };
  }

  /**
   * Verify a Groth16 proof.
   */
  async verify(artifact: ZKArtifact, proof: ZKProof): Promise<boolean> {
    const snarkjs = await this.getSnarkJS();

    if (artifact.verificationKey.length === 0) {
      throw new Error('Verification key not available');
    }

    const vk = JSON.parse(new TextDecoder().decode(artifact.verificationKey));
    const decodedProof = this.decodeProof(proof.proofBytes);
    const publicSignals = proof.publicInputs.map((input) =>
      this.bytesToSignal(input),
    );

    return snarkjs.groth16.verify(vk, publicSignals, decodedProof);
  }

  /**
   * Register a zkey path for a circuit.
   * Call this before prove() if the zkey wasn't available at compile time.
   */
  registerZKey(circuitId: string, zkeyPath: string): void {
    this.zkeyPaths.set(circuitId, zkeyPath);
  }

  // --- Encoding helpers ---

  private witnessToSignals(
    witness: ZKWitness,
  ): Record<string, string | string[]> {
    const signals: Record<string, string | string[]> = {};

    // Map public inputs as indexed signals
    witness.publicInputs.forEach((input, i) => {
      signals[`pub_${i}`] = this.bytesToSignal(input);
    });

    // Map private inputs as indexed signals
    witness.privateInputs.forEach((input, i) => {
      signals[`priv_${i}`] = this.bytesToSignal(input);
    });

    return signals;
  }

  private encodeProof(proof: {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
  }): Uint8Array {
    const bytes = new Uint8Array(256);
    let offset = 0;

    // a[0], a[1]
    this.writeBigInt(bytes, offset, BigInt(proof.pi_a[0]));
    offset += 32;
    this.writeBigInt(bytes, offset, BigInt(proof.pi_a[1]));
    offset += 32;

    // b[0][0], b[0][1], b[1][0], b[1][1]
    this.writeBigInt(bytes, offset, BigInt(proof.pi_b[0][0]));
    offset += 32;
    this.writeBigInt(bytes, offset, BigInt(proof.pi_b[0][1]));
    offset += 32;
    this.writeBigInt(bytes, offset, BigInt(proof.pi_b[1][0]));
    offset += 32;
    this.writeBigInt(bytes, offset, BigInt(proof.pi_b[1][1]));
    offset += 32;

    // c[0], c[1]
    this.writeBigInt(bytes, offset, BigInt(proof.pi_c[0]));
    offset += 32;
    this.writeBigInt(bytes, offset, BigInt(proof.pi_c[1]));

    return bytes;
  }

  private decodeProof(proofBytes: Uint8Array): {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
    protocol: string;
    curve: string;
  } {
    let offset = 0;
    const readBigInt = (): string => {
      const val = this.readBigInt(proofBytes, offset);
      offset += 32;
      return val.toString();
    };

    return {
      pi_a: [readBigInt(), readBigInt(), '1'],
      pi_b: [
        [readBigInt(), readBigInt()],
        [readBigInt(), readBigInt()],
        ['1', '0'],
      ],
      pi_c: [readBigInt(), readBigInt(), '1'],
      protocol: 'groth16',
      curve: 'bn128',
    };
  }

  private signalToBytes(signal: string): Uint8Array {
    const bytes = new Uint8Array(32);
    this.writeBigInt(bytes, 0, BigInt(signal));
    return bytes;
  }

  private bytesToSignal(bytes: Uint8Array): string {
    return this.readBigInt(bytes, 0).toString();
  }

  private writeBigInt(buf: Uint8Array, offset: number, value: bigint): void {
    for (let i = 31; i >= 0; i--) {
      buf[offset + i] = Number(value & 0xffn);
      value >>= 8n;
    }
  }

  private readBigInt(buf: Uint8Array, offset: number): bigint {
    let value = 0n;
    for (let i = 0; i < 32; i++) {
      value = (value << 8n) | BigInt(buf[offset + i]);
    }
    return value;
  }
}
